### ISSUE TITLE
Status bar showing on iPad 8 (iOS 17.0)

### ISSUE THREAD

**Issue by Eggmanplant** [WamWooWam/RSDKv5-Decompilation#6]
Read the title. This doesn't happen in releases lower than 1.3.2. I set pixWidth=1 in settings.ini to make the game display in 4:3. Here are the screenshots: ![IMG_0063](https://private-user-images.githubusercontent.com/126160675/275480007-0be83e1b-e998-4bbc-8a30-a1d515d306f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzU1NzYsIm5iZiI6MTcwNjM3NTI3NiwicGF0aCI6Ii8xMjYxNjA2NzUvMjc1NDgwMDA3LTBiZTgzZTFiLWU5OTgtNGJiYy04YTMwLWExZDUxNWQzMDZmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNzA3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjUyNWRmMzkwM2Y3NDBmNTNiNTk0OWQ4ZGJkZTE2MjdkOGE2ZjM5ZmJlODQ1MmVkMWU3YWVmZTYzZjI3OWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rR0n8PgyOwMFL0c2YQdhFquorlibH7IxENefcD4lmxI) ![IMG_0064](https://private-user-images.githubusercontent.com/126160675/275480014-2b4df81f-f893-48e9-abbc-4052c49284f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzU1NzYsIm5iZiI6MTcwNjM3NTI3NiwicGF0aCI6Ii8xMjYxNjA2NzUvMjc1NDgwMDE0LTJiNGRmODFmLWY4OTMtNDhlOS1hYmJjLTQwNTJjNDkyODRmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNzA3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2FjNWNjNjJkMDhkNzhmYzJmMzcwODFjMTM1MmY2YTFjZWQ4YjQ3MjZmOGJmNDljYTM0MGQwMjYzZGJkYjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tTQuXNHJaEcWJa-yUYe9AFV5zaM4AQPwTYrfjIzfNgs) ![IMG_0065](https://private-user-images.githubusercontent.com/126160675/275480019-6cd96dbe-2dbd-401d-9eb0-9f41ad685b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzU1NzYsIm5iZiI6MTcwNjM3NTI3NiwicGF0aCI6Ii8xMjYxNjA2NzUvMjc1NDgwMDE5LTZjZDk2ZGJlLTJkYmQtNDAxZC05ZWIwLTlmNDFhZDY4NWIwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNzA3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGJiOGUzNGJmYjgwY2RjNWJhMjExNTNiMTU0YjJiNDIxMzVjNWNmYWZhN2EzOGIzMWUyYmI0N2E2NDRmYTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vrgmES7K_ZvwZEwdbqdxsyHNlUZfgZNwOYnCVVUovOg)

**Comment by oo1o1o12** [comment]
why does that bother you in the first place tho?

**Comment by Eggmanplant** [comment]
I want to have an 100% fullscreen experience like in most other iOS games.

**Comment by WamWooWam** [comment]
hi, this should be fixed in the testflight/latest releases :)

**Comment by Eggmanplant** [comment]
Where they are?
