### ISSUE TITLE
IOS mod support???

### ISSUE THREAD

**Issue by Jejear** [WamWooWam/RSDKv5-Decompilation#7]
So I found on android you could add mods and I wondered if you could do it on iOS port I know there’s only specific mods that work with iOS but I tried the way to enter mods on android and it just gave me debug mode instead of dev mode, I ask if u guys made a mod option or can make one or can’t that’s all I’m asking

**Comment by oo1o1o12** [comment]
the mods are actually inside the ipa, you have to edit the file to get mods (the folder is in /RSDKv5.app/Data/)

**Comment by WamWooWam** [comment]
mods are not supported on iOS because of codesigning requirements, you can technically inject them into the IPA but i do not condone this and will not offer support in the event you do
